name: Publish FastModel NuGet Packages
on:
    push:
        tags:
            - 'Release/v*'
jobs:
    build-and-publish:
        runs-on: ubuntu-latest
        
        steps:
            - uses: actions/checkout@v4
            - name: Setup dotnet
              uses: actions/setup-dotnet@v4
              with:
                dotnet-version: '9.0.x'
                
            -   name: Restore dependencies
                run: dotnet restore
            
            -   name: Build all projects
                run: dotnet build --configuration Release --no-restore
            
            -   name: Pack all projects
                run: |
                    mkdir -p ./artifacts
                    dotnet pack src/FastModule.Core/FastModule.Core.csproj --configuration Release --no-build --output ./artifacts
                    dotnet pack src/FastModule.Domain/FastModule.Domain.csproj --configuration Release --no-build --output ./artifacts
                    dotnet pack src/FastModule.EntityFrameworkCore/FastModule.EntityFrameworkCore.csproj --configuration Release --no-build --output ./artifacts
                    dotnet pack src/FastModule.Keycloak/FastModule.Keycloak.csproj --configuration Release --no-build --output ./artifacts
                    dotnet pack src/FastModule.User/FastModule.User.csproj --configuration Release --no-build --output ./artifacts
                    dotnet pack src/FastModule.Shared/FastModule.Shared.csproj --configuration Release --no-build --output ./artifacts
                working-directory: ${{ github.workspace }}
                                   
            -   name: Push all packages to GitHub Package Registry
                run: |
                    for nupkg in ./artifacts/*.nupkg; do
                      dotnet nuget push "$nupkg" --api-key ${{ secrets.NUGET_KEY }} --source "https://api.nuget.org/v3/index.json" --skip-duplicate
                    done
                    
            - name: Notify Discord
              uses: Ilshidur/action-discord@master
              env:
                  DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK_URL }}
              with:
                  args: "🎉 New release published! 🚀\n\n**Packages:**\n- FastModule.Core\n- FastModule.Domain\n- FastModule.EntityFrameworkCore\n- FastModule.Keycloak\n- FastModule.User\n- FastModule.Shared\n\n**Version:** ${{ github.ref_name }}\n\n**Repository:** ${{ github.repository }}"
