name: Publish FastModel NuGet Packages
on:
    push:
        tags:
            - 'Release/v*'
jobs:
    build-and-publish:
        runs-on: ubuntu-latest
        
        steps:
            - uses: actions/checkout@v4
            - name: Setup dotnet
              uses: actions/setup-dotnet@v4
              with:
                dotnet-version: '9.0.x'
                
            -   name: Restore dependencies
                run: dotnet restore
            
            -   name: Build all projects
                run: dotnet build --configuration Release --no-restore
            
            -   name: Pack all projects
                run: |
                    mkdir -p ./artifacts
                    # Function to get the current version of a project
                    get_version() {
                        local csproj_file=$1
                        grep -oP '<Version>\K[^<]+' "$csproj_file"
                    }
    
                    # Function to check if the version has changed
                    version_has_changed() {
                        local csproj_file=$1
                        local nupkg_file=$2
                        local current_version=$(get_version "$csproj_file")
                        
                        if [ -f "$nupkg_file" ]; then
                            local packed_version=$(unzip -p "$nupkg_file" '*.nuspec' | grep -oP '<version>\K[^<]+')
                            if [ "$current_version" == "$packed_version" ]; then
                                return 1 # Version has not changed
                            fi
                        fi
                        return 0 # Version has changed or nupkg does not exist
                    }
    
                    # Pack each project if the version has changed
                    for project in src/FastModule.Core/FastModule.Core.csproj \
                                    src/FastModule.Domain/FastModule.Domain.csproj \
                                    src/FastModule.EntityFrameworkCore/FastModule.EntityFrameworkCore.csproj \
                                    src/FastModule.Keycloak/FastModule.Keycloak.csproj \
                                    src/FastModule.User/FastModule.User.csproj \
                                    src/FastModule.Shared/FastModule.Shared.csproj; do
                        project_name=$(basename "$project" .csproj)
                        current_version=$(get_version "$project")
                        nupkg_file="./artifacts/$project_name.$current_version.nupkg"
                        
                    
                        if version_has_changed "$project" "$nupkg_file"; then
                            echo "Version has changed for $project. Packing..."
                            dotnet pack "$project" --configuration Release --no-build --output ./artifacts
                        else
                            echo "Version has not changed for $project. Skipping pack."
                        fi
                    done
                working-directory: ${{ github.workspace }}
                                   
            -   name: Push all packages to NuGet/FastModule Organization
                run: |
                    for nupkg in ./artifacts/*.nupkg; do
                      dotnet nuget push "$nupkg" -k $NUGET_AUTH_TOKEN -s https://api.nuget.org/v3/index.json
                    done
                env:
                    NUGET_AUTH_TOKEN: ${{ secrets.NUGET_KEY }}
                    
            - name: Notify Discord
              uses: Ilshidur/action-discord@master
              env:
                  DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK_URL }}
              with:
                  args: "🎉 New release published! 🚀\n\n**Packages:**\n- FastModule.Core\n- FastModule.Domain\n- FastModule.EntityFrameworkCore\n- FastModule.Keycloak\n- FastModule.User\n- FastModule.Shared\n\n**Version:** ${{ github.ref_name }}\n\n**Repository:** ${{ github.repository }}"
